### ISSUE TITLE
nebula_messages/velodyne_msgs/package.xml version

### ISSUE THREAD

**Issue by KhalilSelyan** [tier4/nebula#71]
the xml version is 3.0 ? while every other file xml version is 1.0 ? any specific reason ?

**Comment by mitsudome-r** [comment]
Just adding to @KhalilSelyan's comment, this issue was noticed when @KhalilSelyan was trying to parse the package.xml from the library used in https://github.com/leo-drive/autoware-build-gui.

At least wikipedia says that there are only versions 1.0 and 1.1 so I'm doubting that this is likely to be a bug.
https://en.wikipedia.org/wiki/XML

It looks like it was set as version 3.0 since the initial commit from @amc-nu. Do you have any comments on this? 

FYI, this is the part that @KhalilSelyan is referring to:
https://github.com/tier4/nebula/blob/99d3560b2f848d6c4ef998ce56a390c17445eefd/nebula_messages/velodyne_msgs/package.xml#L1

**Comment by mitsudome-r** [comment]
@KhalilSelyan David and Abraham have confirm that this is just a typo. Could you go ahead and create PR?
